version: '3.2'
services:
  artemis:
    image: vromero/activemq-artemis:latest
    ports:
      - "61619:61616"
      - "8162:8162"
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
      ARTEMIS_MIN_MEMORY: 512M
      ARTEMIS_MAX_MEMORY: 1024M
